function TIRFNanocontactsGUI()
%TIRFNanocontactsGUI Creates the GUI, sets callback functions. R2015b
%   
% Kyle Marchuk, PhD
% Biological Imaging Development Center at UCSF
% May 2017
    %% Create the Figure
    figWidth = 400;
    figHeight = 800;
    
    % Set the display position for the GUI
    displayPos = get(0,'MonitorPositions');
    
    if displayPos(1,2) > 0
        figPos = [...
            (displayPos(1,3) - figWidth)/2,...
            (displayPos(1,4) - figHeight)/2,...
            figWidth,figHeight];
    else
        figPos = [...
            (displayPos(2,3) -figWidth)/2,...
            (displayPos(2,4) - figHeight)/2,...
            figWidth,figHeight];
    end % if
    
    guiNC = figure(...
        'Color',[0.1 0.1 0.44],...
        'Colormap',gray(256),...
        'MenuBar','None',...
        'Name','Nanocontacts TIRF',...
        'NumberTitle','Off',...
        'Position',figPos,...
        'Resize','Off',...
        'Tag','guiNC');
    
    %% Create a structure for the parameters and save it as appdata
    % This structure contains the defaults for the GUI. You can edit it
    % here to adapts the default GUI setting to match your preferences. As
    % users edit the parameters in the GUI, these values are updated. It
    % can also be used to store parameters that you do not want users to
    % edit
    
    structParameters = struct(...
        'pathDir','H:\20170511TIRF\1_1',...
        'tcrName','TCRImageStack_OTI_Well1_0_1xN4_1_crop_s.tif',...
        'maskName','MapStack_OTI_Well1_0_1xN4_1_crop_s.tif',...
        'contourName','contourImageStack_OTI_Well1_0_1xN4_1_crop_s.tif',...
        'backgroundCheck',1,...
        'backgroundDisc',10,...
        'gaussianCheck',1,...
        'gaussianSigma',1,...
        'SDoverNoise',3,...
        'xMin',9,...
        'xMax',43,...
        'yMin',5,...
        'yMax',37,...
        'timeRes',1.06,...
        'status','Status: Waiting to Start',...
        'newFolder','NanocontactAnalysis');
    
    setappdata(guiNC,'structParameters',structParameters);
        
    %% Create the TCR file directory boxes
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'Parent',guiNC,...
        'Position',[100 740 200 30],...
        'Style','text',...
        'String','Select TCR Stack File',...
        'Tag','textFileSelect')
    
    handles.displayTCRFile = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiNC,...
        'Position',[10 730 350 20],...
        'String',structParameters.tcrName,...
        'Style','text',...
        'Tag','displayTCRFile');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushTCRFilecallback,guiNC,handles},...
        'FontSize',10,...
        'Parent',guiNC,...
        'Position',[370 730 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','pushTCRFile',...
        'TooltipString','Find the .tif file');
    %% Create the MaskStack file directory boxes
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'Parent',guiNC,...
        'Position',[100 690 200 30],...
        'Style','text',...
        'String','Select Map Stack File',...
        'Tag','textMaskSelect')
    
    handles.displayMaskFile = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiNC,...
        'Position',[10 680 350 20],...
        'String',structParameters.maskName,...
        'Style','text',...
        'Tag','displayMaskFile');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushMaskFilecallback,guiNC,handles},...
        'FontSize',10,...
        'Parent',guiNC,...
        'Position',[370 680 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','pushMaskFile',...
        'TooltipString','Find the .tif file');
    %% Create the ContourStack file directory boxes
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'Parent',guiNC,...
        'Position',[100 640 200 30],...
        'Style','text',...
        'String','Select Contour Stack File',...
        'Tag','textContourSelect')
    
    handles.displayContourFile = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiNC,...
        'Position',[10 630 350 20],...
        'String',structParameters.contourName,...
        'Style','text',...
        'Tag','displayContourFile');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushContourFilecallback,guiNC,handles},...
        'FontSize',10,...
        'Parent',guiNC,...
        'Position',[370 630 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','pushContourFile',...
        'TooltipString','Find the .tif file');
    %% Create the path directory boxes
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',12,...
        'Foreground','w',...
        'Parent',guiNC,...
        'Position',[100 580 200 30],...
        'Style','text',...
        'String','Save Directory',...
        'Tag','textSaveSelect')
    
    handles.displayPathDir = uicontrol(...
        'Background',[0.53 0.80 0.98],...
        'FontSize',10,...
        'ForegroundColor','k',...
        'HorizontalAlign','Left',...
        'Parent',guiNC,...
        'Position',[10 550 350 40],...
        'String',structParameters.pathDir,...
        'Style','text',...
        'Tag','displayPathDir');
    
    uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Callback',{@pushOutputFoldercallback,guiNC,handles},...
        'FontSize',10,...
        'Parent',guiNC,...
        'Position',[370 550 20 20],...
        'String','...',...
        'Style','pushbutton',...
        'Tag','pushOutPath',...
        'TooltipString','Find the save directory');
    %% Create new folder
    checkNewFolder = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'FontSize',12,...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',guiNC,...
        'Position',[125 500 250 20],...
        'String','Create New Folder?',...
        'Style','checkbox',...
        'Tag','checkNewFolder',...
        'TooltipString','Create a new folder within the output directory',...
        'Value',1);
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',11,...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',guiNC,...
        'Position',[100 475 200 20],...
        'Style','text',...
        'String','New Folder Name:',...
        'Tag','textFolderName');
    
    editNewFolder = mycontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'ForegroundColor',[0.53 0.80 0.98],...
        'Parent',guiNC,...
        'Position',[125 450 150 20],...
        'String',structParameters.newFolder,...
        'Style','edit',...
        'Tag','editNewFolder');
    set(editNewFolder.Handle,'Callback',{@editNewFoldercallback,editNewFolder,guiNC})
    %% Create input parameters
    panelRunSettings = uipanel(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor','w',...
        'FontSize',12,...
        'BorderType','Line',...
        'HighlightColor',[0.53 0.80 0.98],...
        'Parent',guiNC,...
        'Position',[25 125 350 300]./[figPos(3) figPos(4) figPos(3) figPos(4)],...
        'Title','Processing Settings',...
        'TitlePosition','Centertop',...
        'Tag','panelRun',...
        'Units','Pixels');
    uistack(panelRunSettings,'bottom')
    
    checkBackground = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[50 250 200 20],...
        'String','Substract Background?',...
        'Style','checkbox',...
        'Tag','checkBackground',...
        'TooltipString','Subtract background before nanocontact analysis',...
        'Value',1);
    
    editTophat = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[220 250 25 20],...
        'Style','edit',...
        'String',structParameters.backgroundDisc,...
        'Tag','editTophat',...
        'TooltipString','Size of background');
    set(editTophat.Handle,'Callback',{@editIntegercallback,editTophat,guiNC})
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[245 250 80 20],...
        'Style','text',...
        'String','Tophat Size',...
        'Tag','textTophat')
    checkGaussian = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[50 225 110 20],...
        'String','Gaussian Blur?',...
        'Style','checkbox',...
        'Tag','checkManual',...
        'TooltipString','Gaussian Blur post processing',...
        'Value',1);
    
    editGaussianSigma = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelRunSettings,...
        'Position',[220 225 25 20],...
        'Style','edit',...
        'String',structParameters.gaussianSigma,...
        'Tag','editGaussianSigma',...
        'TooltipString','Enter Multiplier');
    set(editGaussianSigma.Handle,'Callback',{@editIntegercallback,editGaussianSigma,guiNC})
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[250 225 40 20],...
        'Style','text',...
        'String','Sigma',...
        'Tag','textGaussianSigma')
    %% TCR pos/neg panel
    panelTCR = uipanel(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor','w',...
        'FontSize',12,...
        'BorderType','Line',...
        'HighlightColor',[0.53 0.80 0.98],...
        'Parent',panelRunSettings,...
        'Position',[25 50 350 575]./[figPos(3) figPos(4) figPos(3) figPos(4)],...
        'Title','TCR +/-',...
        'TitlePosition','Centertop',...
        'Tag','panelRun',...
        'Units','Pixels');
    uistack(panelTCR,'bottom')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[1 1 1],...
        'Parent',panelTCR,...
        'Position',[170 155 100 20],...
        'Style','text',...
        'String','ROI Selection',...
        'Tag','textROI')
    
    checkAuto = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelTCR,...
        'Position',[175 135 100 20],...
        'String','Auto',...
        'Style','checkbox',...
        'Tag','checkAuto',...
        'TooltipString','ROI outside contour',...
        'Value',1);
    
    checkManual = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelTCR,...
        'Position',[225 135 200 20],...
        'String','Man',...
        'Style','checkbox',...
        'Tag','checkManual',...
        'TooltipString','User defined ROI',...
        'Value',0);
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[1 1 1],...
        'Parent',panelTCR,...
        'Position',[10 155 125 20],...
        'Style','text',...
        'String','Signal Determination',...
        'Tag','textROI')
    
    checkMean = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelTCR,...
        'Position',[20 135 70 20],...
        'String','Mean',...
        'Style','checkbox',...
        'Tag','checkMean',...
        'TooltipString','Check Mean',...
        'Value',1);
    
    checkMedian = uicontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelTCR,...
        'Position',[80 135 70 20],...
        'String','Median',...
        'Style','checkbox',...
        'Tag','checkMedian',...
        'TooltipString','Check Median',...
        'Value',0);
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelTCR,...
        'Position',[48 100 90 20],...
        'Style','text',...
        'String','SD over Noise',...
        'Tag','textSD')
    
    editSD = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelTCR,...
        'Position',[20 102 25 20],...
        'Style','edit',...
        'String',structParameters.SDoverNoise,...
        'Tag','editSD',...
        'TooltipString','m+#*SD');
    set(editSD.Handle,'Callback',{@editIntegercallback,editSD,guiNC})
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelTCR,...
        'Position',[48 75 90 20],...
        'Style','text',...
        'String','(s) Time Res',...
        'Tag','textTimeRes')
    
    editTimeRes = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelTCR,...
        'Position',[20 75 35 20],...
        'Style','edit',...
        'String',structParameters.timeRes,...
        'Tag','editTimeRes',...
        'TooltipString','Time per Frame');
    set(editTimeRes.Handle,'Callback',{@editTimeResolutioncallback,editTimeRes,guiNC})
    
    
    %% Manual ROI Settings
    panelManualSettings = uipanel(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor','w',...
        'FontSize',11,...
        'BorderType','Line',...
        'HighlightColor',[0.53 0.80 0.98],...
        'Parent',panelTCR,...
        'Position',[200 75 175 500]./[figPos(3) figPos(4) figPos(3) figPos(4)],...
        'Title','Manual',...
        'TitlePosition','Centertop',...
        'Tag','panelManual',...
        'Units','Pixels');
    uistack(panelManualSettings,'bottom')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelManualSettings,...
        'Position',[25 75 50 20],...
        'Style','text',...
        'String','Min',...
        'Tag','textMin')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelManualSettings,...
        'Position',[75 75 50 20],...
        'Style','text',...
        'String','Max',...
        'Tag','textMax')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelManualSettings,...
        'Position',[5 50 25 20],...
        'Style','text',...
        'String','X',...
        'Tag','textX')
    
    uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'FontSize',10,...
        'Foreground',[0.53 0.80 0.98],...
        'Parent',panelManualSettings,...
        'Position',[5 15 25 20],...
        'Style','text',...
        'String','Y',...
        'Tag','textY')
    
    editXMin = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelManualSettings,...
        'Position',[35 55 30 20],...
        'Style','edit',...
        'String',structParameters.xMin,...
        'Tag','editXMin',...
        'TooltipString','Enter x pixel');
    set(editXMin.Handle,'Callback',{@editXcallback,editXMin,guiNC})
    
    editXMax = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelManualSettings,...
        'Position',[85 55 30 20],...
        'Style','edit',...
        'String',structParameters.xMax,...
        'Tag','editXMax',...
        'TooltipString','Enter x pixel');
    set(editXMax.Handle,'Callback',{@editXcallback,editXMax,guiNC})
    
    editYMin = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelManualSettings,...
        'Position',[35 18 30 20],...
        'Style','edit',...
        'String',structParameters.yMin,...
        'Tag','editYMin',...
        'TooltipString','Enter y pixel');
    set(editYMin.Handle,'Callback',{@editYcallback,editYMin,guiNC})
    
    editYMax = mycontrol(...
        'BackgroundColor',[0.1 0.1 0.44],...
        'ForegroundColor',[0.53 0.80 0.98],...
        'FontSize',10,...
        'Parent',panelManualSettings,...
        'Position',[85 18 30 20],...
        'Style','edit',...
        'String',structParameters.yMax,...
        'Tag','editYMax',...
        'TooltipString','Enter y pixel');
    set(editYMax.Handle,'Callback',{@editYcallback,editYMax,guiNC})
    
    %% Create status update
    handles.textStatus = uicontrol(...
        'Background',[0.1 0.1 0.44],...
        'Foreground','w',...
        'FontSize',9,...
        'Parent',guiNC,...
        'Position',[25 75 350 20],...
        'Style','text',...
        'String',structParameters.status,...
        'Tag','textStatus');
    
    %% Create run Button
    uicontrol(...
        'BackgroundColor',[0.53 0.80 0.98],...
        'ForegroundColor',[0.1 0.1 0.44],...
        'Callback',{@pushRun,checkNewFolder,checkMean,checkMedian,checkAuto,checkManual,...
        checkBackground,checkGaussian,guiNC,handles},...
        'FontSize',14,...
        'Parent',guiNC,...
        'Position',[160 10 80 40],...
        'String','RUN!',...
        'Style','pushbutton',...
        'Tag','pushRun',...
        'TooltipString','Go!');

end

